; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env] ; Config commune
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps = fastled/FastLED @ ^3.6.0
build_flags = -I include

[env:crown_c3] ; Pour tes Super Mini
board = esp32-c3-devkitm-1
build_src_filter = +<node_main.cpp>
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:master_wroom] ; Pour ton Master
board = esp32dev
build_src_filter = +<master_main.cpp>